name: osti
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - pandas=2.1.4
  - numpy=1.26.4
  - matplotlib=3.8.0
  - seaborn= 0.12.2
  - pyDOE2=1.3.0
  - psutil=5.9.0
  - scikit-learn=1.3.2
  - pip
  - pip:
    - jupyter
